development:
  adapter: postgresql
  encoding: unicode
  database: rails_app_database
  pool: 5
  host: localhost
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: rails_app_database_test
  pool: 5
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>